# Generated by Django 5.1.3 on 2024-11-19 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_article_title_alter_course_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
