# Generated by Django 5.1.3 on 2024-11-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='login_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
    ]
